dtr-org/unit-e

- src/primitives/txtype.h
**what we want to maintain**
This `TxType` type is used in `Coin` and `snapshot::UTXOSubset` and we serialize
it as `uint8_t` to reduce the disk usage as 256 types of transactions must be
more than enough for all future transactions that we might create.
**possible issue**
Since `TxType` is `uint16_t` there is a risk that we create a record
that will have a number larger than 255 and it will cause incorrect
value to be stored in the Coin or transferred via snapshot.
**proposed fix**
To make it consistent on how this field is used,
we should stick to `uint8_t` everywhere.
Signed-off-by: Kostiantyn Stepaniuk <kostia@thirdhash.com>
> Change TxType type from uint16_t to uint8_t

- test/functional/feature_fork_choice_forked_finalize_epoch.py
- test/functional/test_framework/util.py
Fixes #978 and makes feature_fork_choice_forked_finalize_epoch.py stable.
In #978, @frolosofsky wrote why the test was floating:
> The issue happens because test creates two finalizers which act like being one. Once finalizer2 processes block which includes vote from finalizer1 and at the same moment tries to vote itself, it cannot find corresponding prev transaction in its wallet. This started to happen once #937 is merged, that PR makes validator, when voting, using global validator state instead of local one, and because of two finalizer are actually the same, it made a glitch between two finalizers which started sharing the same validator state.
> I think it's not an issue for production code, we can simply rewrite test to use one validator, but make votes on different branches via …
> Use RPC to vote on parallel chain

- src/wallet/rpcwalletext.cpp
- src/wallet/test/rpcwalletext_tests.cpp
This commit adds a new field called `finalization` to the transactions returned by the `filtertransactions` RPC call, with a value of `true` for finalized transactions and `false` otherwise.
> Return transaction finalization state in filtertransactions

- test/functional/proposer_stakeable_balance.py
The test expects nodes not to be connected.
The test is failing if one of the nodes takes too long to spin up, as some of the other nodes already connect to each other and `assert_equal(wallet['status'], 'NOT_PROPOSING_NO_PEERS')` no longer holds (it's `NOT_PROPOSING_NOT_ENOUGH_BALANCE`).
Signed-off-by: Mateusz Morusiewicz <mateusz@thirdhash.com>
> Fix proposer_stakeable_balance.py

- src/Makefile.am
- src/esperanza/checks.cpp
- src/esperanza/checks.h
- src/esperanza/finalizationstate.cpp
- src/esperanza/script.cpp
- src/esperanza/script.h
- src/esperanza/walletextension.cpp
- src/test/esperanza/checks_tests.cpp
Moves ExtractValidatorPubKey and ExtractValidatorAddress to the esperanza/script.cpp
```diff
< Circular dependency: esperanza/checks -> esperanza/finalizationstate -> esperanza/checks
< Circular dependency: esperanza/finalizationstate -> validation -> esperanza/finalizationstate
< Circular dependency: consensus/tx_verify -> esperanza/finalizationstate -> validation -> consensus/tx_verify
< Circular dependency: esperanza/finalizationstate -> validation -> finalization/vote_recorder -> esperanza/finalizationstate
```
> Reduce circular dependencies in esperanza

- test/functional/example_test.py
Fixes #993 
Wait until the second node will get all blocks.
I ran `example_test.py` ~1000 times with 12 jobs - the issue is gone.
Signed-off-by: Dmitry Saveliev <dima@thirdhash.com>
> Eliminate timing issue with the node syncing in example_test.py

- README.md
Since the spec is outdated there is a PR to remove it https://github.com/dtr-org/unit-e-project/pull/115. We can re-add the links here after we migrated and updated the spec to our doc.
> Remove links to the outdated spec

- contrib/devtools/run-unit-tests.sh
This commit modifies the sort order for the results of run-unit-tests.sh.
Previously, they were sorted lexicographically, which meant that the
failing tests showed on top and could potentially disappear off-screen.
Now, the test results are sorted first by name (from character 6 to the
end of the line), then by status (characters 3 to 5) in reverse order.
Tested on Linux, however, [according to the manpage](https://ss64.com/osx/sort.html), the same options should work on MacOS as well.
> Show failing unit tests at the bottom in run-unit-tests.sh

- src/wallet/wallet.cpp
Workaround for issue #962 .
Although the ideal would be to remove the "deprecated" coinbase
transaction from the wallet, we don't do that because it's not yet clear
what should we do with other transactions that use as input the outputs
of the former one.
So for now I opted for changing the log message in order to distinguish
the coinbase case, which will be far more common than the case where the
user manually generates conflicting transactions after a re-org.
Signed-off-by: Andres Correa Casablanca <andres@thirdhash.com>
> Workaround for issue 962

- test/functional/feature_commits_forkchoice.py
By invoking `generatetoaddress`/`getnewaddress` once per batch
the execution time is reduced by 2.5 times.
On my MacBook 2.8 GHz Intel Core i7 I see the following gain.
Before:
```
/usr/local/bin/python3.7 /Users/kostiantyn/github.com/kostyantyn/unit-e/test/functional/feature_commits_forkchoice.py
2019-04-29 16:23:33.309000 TestFramework (INFO): Initializing test directory /var/folders/r9/s635cnq5265dp3bgh1kcw7b40000gn/T/testipslakwa
2019-04-29 16:23:33.310000 TestFramework (INFO): Debug file at /var/folders/r9/s635cnq5265dp3bgh1kcw7b40000gn/T/testipslakwa/node0/regtest/debug.log
Starting node 0 with args: -esperanzaconfig={"epochLength": 10, "minDepositSize": 1500}
Starting node 1 with args: -esperanzaconfig={"epochLength": 10, "minDepositSize": 1500}
Starting node 2 with args: …
```
> Speedup feature_commits_forkchoice.py

- test/functional/p2p_compactblocks.py
- test/functional/p2p_segwit.py
- test/functional/test_framework/blockstore.py
- test/functional/test_framework/messages.py
Fixes #1032, Follow up to #1029
Removes the `with_witness` named argument from `CBlock.serialize()`. `p2p_segwit` requires non-witness serialization for computing the proper block weight, which is why an explicit `serialize_without_witness` has been added (this is the same as existing design on `CTransaction`).
Drops `msg_witness_blocktxn` in favor of `msg_blocktxn`, which now uses serialization with witness by default and unconditionally.
> Functional tests witness messages follow up

- src/bloom.cpp
- src/bloom.h
As you know, C++ standard does not explicitly define how many bits should be there in `char` or `int`. And while currently, in absolute majority of cases, it is 8 and 32 bits respectively, leaving the things as is a potential way to shoot yourself in a leg.
[sizeof operator](https://en.cppreference.com/w/cpp/language/sizeof)
[fundamental types](https://en.cppreference.com/w/cpp/language/types)
And while we can follow this rule and change everything, I believe that we should start with protocol first. Because compiling unit-e on a system, which uses 16 bit int, or a char that is >8 bits will break the CBloomFilter.
Signed-off-by: Aleksandr Mikhailov <aleksandr@thirdhash.com>
> Adjust types in CBloomFilter

- src/blockchain/blockchain_parameters.cpp
Given that some consensus parameters (like reward) are in part derived from the chain parameter stating which is the expected initial supply, to ensure consistency, we should assert that the constant is actually correct.
This commit adds such assertion, checking the constant against the initial supply created in the genesis block.
Signed-off-by: Andres Correa Casablanca <andres@thirdhash.com>
> Add check for the genesis block's supply

- test/functional/test_runner.py
Disable it at the memont, because it flakes too often and disturbs further development by triggering
Travis builds. There is an issue (#1042) to fix the test.
> Disable flaky wallet_labels test

- test/functional/esperanza_slash.py
- test/functional/esperanza_slash_restart.py
- test/functional/esperanza_vote.py
- test/functional/esperanza_vote_reorg.py
- test/functional/esperanza_withdraw.py
- test/functional/feature_commits_forkchoice.py
- test/functional/feature_finalizer.py
- test/functional/feature_fork_choice_finalization.py
- test/functional/feature_fork_choice_forked_finalize_epoch.py
- test/functional/feature_fork_choice_parallel_justifications.py
- test/functional/feature_no_esperanza_tx_relay_delay.py
- test/functional/feature_reindex_commits.py
- test/functional/feature_snapshot.py
- test/functional/feature_snapshot_creation.py
- test/functional/feature_snapshot_finalization.py
- test/functional/finalization_deposit_reorg.py
- test/functional/finalization_slash_itself.py
- test/functional/finalization_state_restoration.py
- test/functional/p2p_snapshot.py
- test/functional/rpc_finalization.py
- test/functional/rpc_getblocksnapshot.py
- test/functional/test_framework/util.py
At the moment, the way we generate blocks in functional tests is quite meditative and repeatable.
This commit factors out simple function generate_block that eliminates the need to copy-paste every
time we generate new blocks in tests.
Conceptually, the change is:
```diff
-node.generatetoaddress(10, node.getnewaddress('', 'bech32'))
+generate_block(node, count=10)
```
`count=1` is omitted.
The script which makes dirty job:
```bash
for f in $(git grep -l generatetoaddress '*finalization*.py' '*esperanza*.py' '*snapshot*.py' '*commits*.py' '*finalizer*.py' '*forkchoice*.py' '*fork_choice*.py'); do
echo $f
LANG=C LC_CTYPE=C sed -e 's/\([][a-z0-9_.]*\)\.generatetoaddress(1, \1\.getnewaddress(.*, .*))/generate_block(\1)/' -i '' $f
LANG=C LC_CTYPE=C sed -e …
```
> Factor out generate_block function

- src/better-enums/enum_set.h
- src/rpc/mining.cpp
- src/test/better_enum_set_tests.cpp
- src/wallet/rpcmnemonic.cpp
- src/walletinitinterface.h
Compressed list of fixed warnings:
* ./walletinitinterface.h:14:1: warning: struct 'WalletExtensionDeps' was previously declared as a class [-Wmismatched-tags]
* rpc/mining.cpp:76:20: warning: unused function 'gbt_vb_name' [-Wunused-function]
* wallet/rpcmnemonic.cpp:92:19: warning: loop variable 'language' of type 'const key::mnemonic::Language' creates a copy from type 'const key::mnemonic::Language' [-Wrange-loop-analysis]
* test/better_enum_set_tests.cpp:216:20: warning: loop variable 'e' is always a copy because the range of type 'EnumSet<SomeTestEnum>' does not return a reference [-Wrange-loop-analysis]
* ./better-enums/enum_set.h:66:21: warning: loop variable 'e' of type 'const SomeTestEnum' creates a copy from type 'const SomeTestEnum' [-Wrange-loop-analysis]
> Fix compilation warnings appeared after bitcoin-0.17 merge

- test/functional/test_framework/test_node.py
This commit hardens the regular `wallet_multiwallet.py`, which can fail
just like the `--usecli` version, for the reasons detailed in commit ad7c2e72:
when the node is already stopping, we can get all kinds of network exceptions
when trying to stop it a second time, so we want to ignore those exceptions.
> Fix wallet_multiwallet.py

- src/test/util_tests.cpp
On macOS the following call:
```
src/test/test_unite --run_test=util_tests_datadir/test_LockDirectory
```
Fails:
```
Running 1 test case...
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
test/util_tests.cpp:1342: error: in "util_tests_datadir/test_LockDirectory": check processstatus == 0 has failed [11 != 0]
*** 1 failure is detected in the test module "Unit-e Test Suite"
```
The test itself fails as the `BOOST_CHECK` which checks that the child process terminated correctly is trigger (as the child does not terminate correctly). The unit test actually forks (sic!) the process. The forked process actually works fine too and only blows up on calling `exit`.
This pull request changes the call to …
> Fix unit test: util_tests_datadir/test_LockDirectory 

- src/esperanza/walletextension.cpp
- test/functional/esperanza_admin_full_cycle.py
At the moment, when a user prepares deposit, the node creates a transaction and adds it to the
wallet.  It, in turn, tries to accept it to the memory pool and could fail when the deposit is
invalid (for example validator is blacklisted). That leads to disappearing of the deposit from the
balance.
This commit fixes that by validating deposit before adding transaction to the wallet.
Fixes #996.
> Validate deposit prior adding to the wallet

- test/functional/test_runner.py
- test/functional/wallet_labels.py
The test encountered two synchronization issues:
In the first case, node A generated blocks, then sent some of the
generated funds to node B. However, node B didn't always manage to sync
the blockchain before receiving the transaction, so it would discard the
transaction as an orphan, and not include it in the next mined block.
The second case was similar: node B generated funds to node A's address,
however, node A did not manage to sync the blockchain and add the funds
to the wallet before it was asked to create a new transaction with them.
Fixes #1042.
> Fix wallet_labels.py

- src/prevector.h
This PR cherry-picks a Bitcoin commit which fixes GCC's `-Wmaybe-uninitialized` for a couple of methods in prevector.h.
> Fix GCC warnings in prevector.h by initializing class fields

- .pep8speaks.yml
Based on the example config from https://pep8speaks.com/.
Rationale: The default PEP8 line length is sometimes not enough for expressivity. See also https://medium.com/@drb/pep-8-beautiful-code-and-the-tyranny-of-guidelines-f96499f5ac17 .
> Increase the max line length for pep8speaks to 120 characters

- src/Makefile.test.include
Previously, the Makefile scripts for each individual unit test were
displayed for debugging purposes. This commit suppresses this output,
which should make the Travis log smaller.
Note that, just after the unit tests, we also test `unit-e-tx`, which also
prints its testcases. This output should not be suppressed, since the
test takes a long time, and the Travis build can timeout if it doesn't
see any output for a while.
> Reduce Travis log spam

- src/esperanza/walletextension.cpp
- src/esperanza/walletextension.h
- src/staking/stakingwallet.h
- src/test/proposer/block_builder_tests.cpp
This PR adds a new method `GetName()` to `staking::StakingWallet`. This is a prerequisite to https://github.com/dtr-org/unit-e/pull/1051. The main reason is that is convenient to have a label attached to each wallet so that we can distinguish between them while logging/debugging.
> Add GetName to staking wallet

- test/functional/feature_assumevalid.py
This commit is an alternative to https://github.com/dtr-org/unit-e/pull/1056
The motivation for this change is to speed up the test, as by increasing the epoch length, we
reduce the number of snapshots the node generates.
I am still in favor of keeping snapshot generation enabled by default to ensure we test that component in every scenario possible.
Signed-off-by: Kostiantyn Stepaniuk <kostia@thirdhash.com>
> Set epochLength=200 in feature_assumevalid.py

- src/staking/legacy_validation_interface.h
Removes the `New` factory function declaration from `LegacyValidationInterface`. The function does not have a definition in the `*.cpp` counterpart.
> Remove function without implementation from LegacyValidationInterface

- src/esperanza/walletextension.cpp
- src/test/mempool_tests.cpp
- src/usbdevice/rpcusbdevice.cpp
- test/functional/p2p_fingerprint.py
During the #1062 a couple of minor problems was found:
- `GetVirtualTransactionSize` must have a `sigOpCost` as an argument. Right now this test passes just by coincidence.
- In `p2p_fingerprint.py` we need to take unspent coins before the substituted subchain.
- Clang formatting
Signed-off-by: Dmitry Saveliev <dima@thirdhash.com>
> Minor adjustments for the tests and codestyle

- src/esperanza/finalizationstate.cpp
- src/esperanza/finalizationstate_data.cpp
- src/esperanza/finalizationstate_data.h
- src/test/esperanza/finalizationstate_utils.cpp
Make `m_last_voter_rescale` and `m_last_non_voter_rescale` local variables
to reduce the size of FinalizationState and have a better understanding of how and
where these fields are used
Signed-off-by: Kostiantyn Stepaniuk <kostia@thirdhash.com>
> Convert two fields of FinalizationState to local variables

- src/injector.h
- src/miner.cpp
- src/proposer/block_builder.cpp
- src/proposer/block_builder.h
- src/proposer/proposer.cpp
- src/proposer/proposer.h
- src/proposer/proposer_logic.cpp
- src/proposer/proposer_rpc.cpp
- src/proposer/proposer_rpc.h
- src/rpc/parameter_conversion.cpp
- src/rpc/proposing.cpp
- src/staking/block_validator.cpp
- src/test/esperanza/walletextension_tests.cpp
- src/test/proposer/block_builder_tests.cpp
- src/test/proposer/proposer_tests.cpp
- test/functional/feature_block.py
- test/functional/proposer_settings.py
- test/functional/proposer_stake_maturity.py
- test/functional/rpc_propose.py
- test/functional/test_runner.py
This PR introduces two 2 RPC commands, `propose` and `proposetoaddress` their goal is to mimic bitcoin's `generate` and `generatetoaddress`, with the difference that they use our new proposing mechanism instead. The goal is to migrate all the calls from all the functional tests to this new RPCs.
> New RPC propose and proposetoaddress

- src/consensus/tx_verify.cpp
- src/consensus/tx_verify.h
- src/staking/legacy_validation_interface.cpp
This removes the `fCheckDuplicateInputs` flag from `CheckTransaction` in `consensus/tx_verify.cpp`.
This flag was subject to a CVE in bitcoin (See the full disclosure posting in their blog: https://bitcoincore.org/en/2018/09/20/notice/).
Ever since the CVE was fixed this flag is never passed as `false` and you must not not check it. Also the behavior is not checked with the parameter `false` in any test, as can be seen from this pull request as no test had to be touched yet everything passes.
> Remove fCheckDuplicateInputs flag from CheckTransaction

- contrib/devtools/circular-dependencies.py
- contrib/devtools/copyright_header.py
- contrib/devtools/test_copyright_header.py
- contrib/filter-lcov.py
- src/blockchain/regtest_funds.cpp
- src/blockchain/testnet_funds.cpp
- src/finalization/state_processor.cpp
- src/staking/block_validation_info.cpp
- src/staking/block_validation_info.h
- src/staking/validation_error.cpp
- src/staking/validation_error.h
- src/staking/validation_result.cpp
- src/staking/validation_result.h
- src/trit.cpp
- test/functional/feature_graphene_active.py
- test/functional/feature_remote_staking.py
- test/functional/p2p_embargoman_star.py
- test/functional/proposer_remote_staking.py
* Add copyright headers to files which didn't have one yet
* Fix format of Unit-e copyright headers to be consistent
* Adapt `copyright_headers.py` to not take merge commits into
account when calculating the date of the last change
* Add missing copyright holders to list of known copyright holders
in `copyright_headers.py`
* Update years in copyright notice for the files which have
been updated in 2019 without updating the notice by running
`copyright_headers.py update`
* Remove empty file `test/functional/test_framework/blockstore.py`
> Update copyright headers

- src/test/validation_tests.cpp
Currently we are using the "old" bitcoin validation functions, wrapped in the `LegacyValidationInterface`, as introduced when finally removing Proof-of-Work in https://github.com/dtr-org/unit-e/pull/929. In that pull request we hid the existing validation functions behind an interface so we could swap out the legacy function against the new ones from `staking::BlockValidator` - featuring the same interface.
Ultimately we want to use the new `staking::BlockValidator` which is not in use currently. In order to verify that a second implementation of the `LegacyValidationInterface` which will delegate to `staking::BlockValidator` does the same validations as the existing functions it would be nice to have a way of running the same unit test suite against different instances of it.
This pull …
> Use fixture templates to allow running same tests on different implementations

- test/lint/commit-script-check.sh
GitHub inserts line endings using CRs in some cases when squashing
commits. This causes issues in case of scripted diffs where the
script is extracted from the commit message by `commit-script-check.sh`.
This patch fixes this by removing CRs at the end of the line before
extracting the script for checking the commit.
This issue made the lint check on https://github.com/dtr-org/unit-e/pull/1083 fail. With this patch the lint check should work again on that PR.
You can test the change locally by calling `commit-script-check.sh` manually with a commit range which includes a scripted diff. I tested with `test/lint/commit-script-check.sh 9978e63..a52d88e` which is the commit with the scripted diff we added in #1072.
> Fix scripted diffs with CRs in the commit message

- src/coins.h
- test/functional/feature_snapshot_finalization.py
As was requested by @scravy here https://github.com/dtr-org/unit-e/pull/1081#discussion_r282037133, I extracted this tiny fix.
> Fix some comments

- src/esperanza/finalizationstate.cpp
- src/esperanza/finalizationstate.h
- src/finalization/params.h
- src/test/esperanza/finalizationstate_tests.cpp
- src/test/finalization/params_tests.cpp
`GetEpoch`, `IsEpochStart`, and `IsCheckpoint` do not depend on the finalization state and hence should be moved to `finalization::Params`.
Extracted from #1081.
> Move GetEpoch, IsEpochStart, and IsCheckpoint to finalization::Params

- src/esperanza/finalizationstate.cpp
- src/test/esperanza/checks_tests.cpp
- src/test/esperanza/finalizationstate_vote_tests.cpp
- test/functional/finalization_vote.py
This fix significantly reduces individual finalization state size.
In a test, I run 1 proposer with 4 finalizers with configuration epoch_length=2.
After processing ~9k blocks and ~4.5k epochs, finalization state size was 767599.
After applying this PR, it has been reduced to 196002. More finalizers we have,
more memory we save, because checkpoints map holds votes from every finalizer.
Relates to #1073.
> Cleanup old checkpoints from finalization state

- src/Makefile.test.include
- src/test/finalization/state_db_tests.cpp
- src/test/finalization/state_processor_tests.cpp
- src/test/finalization/state_repository_tests.cpp
- src/test/finalizer_commits_handler_tests.cpp
- src/test/proposer/proposer_logic_tests.cpp
- src/test/proposer/proposer_tests.cpp
- src/test/staking/stake_validator_tests.cpp
- src/test/test_unite_mocks.h
- src/test/tx_verify_tests.cpp
- src/test/util/blocktools.cpp
- src/test/util/blocktools.h
- src/test/util/blocktools_tests.cpp
- src/test/util/mocks.cpp
- src/test/util/mocks.h
- src/wallet/test/wallet_test_fixture.cpp
This introduces a unified interface to the mocks in `test_unite_mocks.h`. So far the mocks were growing uncontrolled and some were more like fakes, stubs, and whatever you want to call these things. Most important however: Some of them were different in spirit from other ones.
Now every Mock (every class ending in `*Mock`) has a member field for every overloaded function called `mock_NameOfThatFunction`. That function can be stubbed (using `SetStub`), the result to be returned can be set (using `SetResult`), the invocations of a particular method can be checked (`CountInnovations`) and the number of times a Mock was interacted with (`CountInteractions`).
In order to streamline the mocks I needed to touch a few tests, most heavily I touched `state_db_tests`. In order to wrap my head around …
> Uniform Mocks + Blocktool for faking block index

- .travis/test_06_script.sh
- test/util/unite-util-test.py
By default, Travis kills the build if more than 10 minutes pass without
any output on screen. After the PR #1065 was merged, [this regularly happens](https://travis-ci.com/dtr-org/unit-e/jobs/197972202#L3384)
with our Windows build .
This commit restores the keepalive changes from #115 that were lost with the 0.17 merge.
> Restore unit test keepalives in Travis

- src/staking/legacy_validation_interface.cpp
- src/staking/legacy_validation_interface.h
- src/test/validation_tests.cpp
- src/validation.cpp
Ever since `pow.h` has been removed Proof-of-Work is no longer checked and Proof-of-Stake is our consensus algorithm of choice.
This removes the remaining flags which conditionally check PoW. Already these flags have not been used and/or passed as `false` only.
> Remove check_proof_of_work flag

- src/Makefile.am
- src/Makefile.test.include
- src/consensus/tx_verify.cpp
- src/injector.h
- src/staking/block_reward_validator.cpp
- src/staking/block_reward_validator.h
- src/test/staking/block_reward_validator_tests.cpp
- src/test/tx_verify_tests.cpp
- src/validation.cpp
Fixes #777.
Extracted from #1081 because it contains important changes to coinbase validation which can be easily overlooked.
This PR implements the following rules for coinbase transactions:
1. The output amount minus the input amount must not be bigger than the block reward plus fees.
2. The output amount minus the input amount must not be smaller than the block reward. It allows proposers to burn fees. I did it this way because many functional tests generate coinbase transactions without taking into account fees.
3. Non-reward output amount (sum of all outputs except the first one) must not be bigger than the input amount.
Note that the first output (which is subject to coinbase maturity) can be bigger than the block reward plus fees, i.e. the reward and the stake can be sent to one …
> Block reward validation

- src/test/esperanza/walletextension_tests.cpp
- src/test/txvalidationcache_tests.cpp
- src/wallet/test/wallet_test_fixture.cpp
- src/wallet/test/wallet_test_fixture.h
- src/wallet/test/wallet_tests.cpp
This PR replaces the `BlockAssembler` with the `BlockBuilder` while building blocks for the `Test100ChainSetup`.
> TestChain100Setup: Replace BlockAssembler with BlockBuilder

- test/functional/feature_commits_forkchoice.py
Sometimes the proposer p0 generated blocks faster than the finalizer v0 cast its votes. Because of that the fourth epoch was not always finalized. This PR makes the test one epoch shorter and makes finalization of the third epoch deterministic.
> Fix feature_commits_forkchoice

- src/staking/block_validator.cpp
- src/staking/block_validator.h
- src/staking/stake_validator.cpp
- src/staking/validation_error.cpp
- src/staking/validation_result.cpp
- src/staking/validation_result.h
- src/test/proposer/block_builder_tests.cpp
- src/test/staking/abstract_block_validator_tests.cpp
- src/test/staking/block_validator_tests.cpp
- src/test/staking/stake_validator_tests.cpp
- src/test/test_unite_mocks.h
- src/validation.cpp
This changes `BlockValidationResult` from hosting a set of validation errors to just carry one validation error and always short circuit / return early on validation errors.
This was already suggested during the initial review of this by @kostyantyn 
Some things that follow: Some tests had to be set up a bit differently as previously multiple things could fail, now the first thing fails and some fixtures were not mocked accordingly. This fixes that.
Cosmetic changes:
- removes a few `auto` in favor of proper types in tests
- uses a few `BOOST_CHECK_MESSAGE` instead of `BOOST_CHECK` for better debugging
> Simplify BlockValidationResult

- contrib/githooks/pre-commit
The #1101 broke pre-commit git hook by moving linter from `contrib/devtools` to`test/lint`
directory. This commit fixes that.
> Fix pre-commit hook

- src/test/staking/block_reward_validator_tests.cpp
test/staking/block_reward_validator_tests.cpp:28:29: warning: lambda capture 'this' is not used
> Fix compilation warning

- CONTRIBUTING.md
- SECURITY.md
Move security policy to SECURITY.md so it shows up on the new Security tab on GitHub.
> Move security policy to own file

- doc/developer-notes.md
There is a dead link for the clang-fromat linter. This PR fixes it.
> Fix dead link in the docs for the clang-format git hook

- src/validation.h
Unused declarations:
- `RewindBlockIndex` is duplicated (see lines 410 and 416)
- `IsNullDummyEnabled` is not used and lacks a definition in `*.cpp`
- same with `UpdateUncommittedBlockStructures`
> Remove unused code

- src/blockdb.cpp
- src/index/base.cpp
- src/net_processing.cpp
- src/p2p/finalizer_commits_handler_impl.cpp
- src/p2p/graphene_sender.cpp
- src/rest.cpp
- src/rpc/blockchain.cpp
- src/rpc/rawtransaction.cpp
- src/snapshot/rpc_processing.cpp
- src/validation.cpp
- src/validation.h
- src/wallet/rpcwallet.cpp
- src/wallet/wallet.cpp
- src/zmq/zmqpublishnotifier.cpp
The consensus params parameter on `ReadBlockFromDisk` was not used, removed; and changed all invocations accordingly.
> Remove arguments that are not required

- src/Makefile.test.include
- src/net_processing.cpp
- src/net_processing.h
- src/test/esperanza/walletextension_tests.cpp
- src/test/new_pos_valid_block_tests.cpp
- src/test/txvalidationcache_tests.cpp
- src/validation.cpp
- src/validationinterface.cpp
- src/validationinterface.h
- src/wallet/test/wallet_test_fixture.cpp
- src/wallet/test/wallet_test_fixture.h
- test/functional/feature_block.py
Fixes #903 
High-bandwidth compact block relay can sometimes relay invalid blocks, however PoW check ensures that it is hard to create many of such blocks to cause any issues. After removing PoW we have lost this protection.
This PR introduces new `AcceptStake` function, which performs full stake validation as a part of `AcceptBlock`. At the moment this validation is only performed when new block extends active chain. 
Behaviour in case of fork is unchanged and subject to a separate feature/PR(which I am working on in parallel).
Signed-off-by: Aleksandr Mikhailov <aleksandr@thirdhash.com>
> Check stake before relaying high perf compact block

- src/finalization/state_db.cpp
- src/finalization/state_db.h
- src/finalization/state_repository.cpp
- src/test/esperanza/finalizationstate_utils.cpp
- src/test/finalization/state_db_tests.cpp
- src/test/finalization/state_repository_tests.cpp
- src/test/test_unite_mocks.h
We've noticed that finalization state storage aggressively consumes disk space that leads
to the out-of-disk condition. This commit fixes that by deleting old states from disk the
same way as we trim repository in memory.
Besides that:
* Fix `Rand<bool>` from finalizationstate_utils.cpp;
* For DBWrapper, use composition instead of inheritance in StateDBImpl.
> Delete old finalization states from disk
